### ISSUE TITLE
[compile error]src\oregoncore\OregonCore.rc(55): error RC2127: version WORDs separated by commas expected

### ISSUE THREAD

**Issue by zhy9934** [OregonCore/OregonCore#1259]
after update Core/Crashes: Update Wheaty
occour a compile error
src\oregoncore\OregonCore.rc(55): error RC2127: version WORDs separated by commas expected
src\oregoncore\OregonCore.rc(55): error RC2167: unrecognized VERSIONINFO field;  BEGIN or comma expected

i need help ,please

**Comment by Zaffy** [comment]
This should have been fixed already. Try retuning cmake

**Comment by zhy9934** [comment]
after cmake ,this error still occour 
i want to know what is related to this error? thanks!

**Comment by Zaffy** [comment]
Try rebuilding revision.h or simply delete it from your build dir. It will be rebuilt automatically.

The error was with genrev and one missing variable

**Comment by zhy9934** [comment]
OK .the error is resolved.thanks 

i close it

**Comment by kotishe** [comment]
http://d.mlx.su/104e0c5072d344dd/patch.diff fix for bug
